import { Product, Supplier } from "./product.types"

export const productData: Product[] = [
  {
    id: 1,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 2,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboniere Vidro Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 3,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboniere Vidro",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 4,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de pratos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 5,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Condimentos Giratorio",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 6,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Chaleira Cinza",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 8000,
  },
  {
    id: 7,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto de pratos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 8,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Chaleira Pequena",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 9,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Potes Pequenos Microondas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1000,
  },
  {
    id: 10,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cafeteira Nespresso",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 20000,
  },
  {
    id: 11,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bule Chá",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1500,
  },
  {
    id: 12,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Queijo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 13,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Suporte Café",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1000,
  },
  {
    id: 14,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Potes Vidro Palha",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 4000,
  },
  {
    id: 15,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sanduicheira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 4000,
  },
  {
    id: 16,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Ovos Galinha",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 1200,
  },
  {
    id: 17,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Ovos Bege",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 18,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Garrafa Térmica 1L",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 19,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "1 Cortina Bege",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
  },
  {
    id: 20,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pote Pêra",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 21,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pote Laranja",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 22,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto Listrado Verde",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
  },
  {
    id: 23,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Microondas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1500,
  },
  {
    id: 24,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 25,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortina",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 6000,
  },
  {
    id: 26,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Maquina de fazer Donuts",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 8000,
  },
  {
    id: 27,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboneira/Doceira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 28,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 0,
  },
  {
    id: 29,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Termometro de cozinha",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1500,
  },
  {
    id: 30,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Luva & Avental",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 31,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Facas",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 4000,
  },
  {
    id: 32,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija de Vidro Marinex",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 1500,
  },
  {
    id: 33,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Panela Churrasqueira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 7000,
  },
  {
    id: 34,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Impressora sem cartucho",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 15000,
  },
  {
    id: 35,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Garrafa Térmica com xícaras",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 36,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortador de verduras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 37,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sapato Preto Masculino",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
  },
  {
    id: 38,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "3 Potes Lilás de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
]
