import { Product, Supplier } from "./product.types"

export const productData: Product[] = [
  {
    id: 1,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
    purchaser: "",
  },
  {
    id: 2,
    urlPhoto: ["/product-photos/bomboniere-vidro-lyor-1.jpg", "/product-photos/bomboniere-vidro-lyor-2.jpg"],
    name: "Bomboniere Vidro Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
    purchaser: "",
  },
  {
    id: 3,
    urlPhoto: ["/product-photos/bomboniere-vidro-1.jpg", "/product-photos/bomboniere-vidro-2.jpg"],
    name: "Bomboniere Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
    purchaser: "",
  },
  {
    id: 4,
    urlPhoto: ["/product-photos/jogo-pratos-18pcs-1.jpg", "/product-photos/jogo-pratos-18pcs-2.jpg", "/product-photos/jogo-pratos-18pcs-3.jpg", "/product-photos/jogo-pratos-18pcs-4.jpg", "/product-photos/jogo-pratos-18pcs-5.jpg", "/product-photos/jogo-pratos-18pcs-6.jpg", "/product-photos/jogo-pratos-18pcs-7.jpg", "/product-photos/jogo-pratos-18pcs-8.jpg", "/product-photos/jogo-pratos-18pcs-9.jpg", "/product-photos/jogo-pratos-18pcs-10.jpg", "/product-photos/jogo-pratos-18pcs-11.jpg", "/product-photos/jogo-pratos-18pcs-12.jpg", "/product-photos/jogo-pratos-18pcs-13.jpg", "/product-photos/jogo-pratos-18pcs-14.jpg", "/product-photos/jogo-pratos-18pcs-15.jpg"],
    name: "Jogo de pratos 18 peças (pires, prato de sobremesa, fundo e raso)",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
    purchaser: "",
  },
  {
    id: 5,
    urlPhoto: "/product-photos/porta-condimentos-giratorio.jpg",
    name: "Porta Condimentos Giratorio",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
    purchaser: "",
  },
  {
    id: 6,
    urlPhoto: ["/product-photos/chaleira-cinza-1.jpg", "/product-photos/chaleira-cinza-2.jpg"],
    name: "Chaleira Cinza",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 8000,
    purchaser: "",
  },
  {
    id: 7,
    urlPhoto: ["/product-photos/kit-potinhos-empratados-8pcs-1.jpg", "/product-photos/kit-potinhos-empratados-8pcs-2.jpg", "/product-photos/kit-potinhos-empratados-8pcs-3.jpg", "/product-photos/kit-potinhos-empratados-8pcs-4.jpg", "/product-photos/kit-potinhos-empratados-8pcs-5.jpg"],
    name: "Kit Potinhos Empratados 8 peças",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
    purchaser: "",
  },
  {
    id: 8,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Chaleira Pequena",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.MIRIAM,
    price: 3000,
    purchaser: "",
  },
  {
    id: 9,
    urlPhoto: ["/product-photos/kit-potes-vidro-tampa-decorativa-4pcs-1.jpg", "/product-photos/kit-potes-vidro-tampa-decorativa-4pcs-2.jpg", "/product-photos/kit-potes-vidro-tampa-decorativa-4pcs-3.jpg", "/product-photos/kit-potes-vidro-tampa-decorativa-4pcs-4.jpg", "/product-photos/kit-potes-vidro-tampa-decorativa-4pcs-5.jpg"],
    name: "Kit Potes Vidro Tampa Decorativa 4pcs",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
    purchaser: "",
  },
  {
    id: 10,
    urlPhoto: ["/product-photos/cafeteira-nespresso-1.jpg", "/product-photos/cafeteira-nespresso-2.jpg"],
    name: "Cafeteira Nespresso",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 20000,
    purchaser: "",
  },
  {
    id: 11,
    urlPhoto: ["/product-photos/placeholder.svg"],
    name: "Bule Chá",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1500,
    purchaser: "",
  },
  {
    id: 12,
    urlPhoto: ["/product-photos/porta-queijo-1.jpg", "/product-photos/porta-queijo-2.jpg", "/product-photos/porta-queijo-3.jpg", "/product-photos/porta-queijo-4.jpg"],
    name: "Porta Queijo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
    purchaser: "",
  },
  {
    id: 13,
    urlPhoto: ["/product-photos/suporte-cafe-1.jpg", "/product-photos/suporte-cafe-2.jpg"],
    name: "Suporte Café",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1000,
    purchaser: "",
  },
  {
    id: 14,
    urlPhoto: "/product-photos/kit-potes-vidro-palha-2pcs.jpg",
    name: "2 Potes Vidro Palha",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 4000,
    purchaser: "",
  },
  {
    id: 15,
    urlPhoto: ["/product-photos/sanduicheira-1.jpg", "/product-photos/sanduicheira-2.jpg", "/product-photos/sanduicheira-3.jpg"],
    name: "Sanduicheira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
    purchaser: "",
  },
  {
    id: 16,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Ovos Galinha",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 1200,
    purchaser: "",
  },
  {
    id: 17,
    urlPhoto: "/product-photos/porta-ovos-bege.jpg",
    name: "Porta Ovos Bege",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
    purchaser: "",
  },
  {
    id: 18,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Garrafa Térmica 1L",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 19,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "1 Cortina Bege",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
    purchaser: "",
  },
  {
    id: 20,
    urlPhoto: ["/product-photos/pote-pera-chocolate-1.jpg", "/product-photos/pote-pera-chocolate-2.jpg"],
    name: "Pote Pêra Chocolate",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
    purchaser: "",
  },
  {
    id: 21,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pote Laranja",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
    purchaser: "",
  },
  {
    id: 22,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto Listrado Verde",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
    purchaser: "",
  },
  {
    id: 23,
    urlPhoto: "/product-photos/prato-microondas.jpg",
    name: "Prato Microondas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1500,
    purchaser: "",
  },
  {
    id: 24,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 25,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortina",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 6000,
    purchaser: "",
  },
  {
    id: 26,
    urlPhoto: "/product-photos/maquina-donuts.jpg",
    name: "Maquina de fazer Donuts",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 8000,
    purchaser: "",
  },
  {
    id: 27,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboneira/Doceira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 28,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 0,
    purchaser: "",
  },
  {
    id: 29,
    urlPhoto: ["/product-photos/termometro-cozinha-1.jpg", "/product-photos/termometro-cozinha-2.jpg"],
    name: "Termometro de cozinha",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1500,
    purchaser: "",
  },
  {
    id: 30,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Luva & Avental",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 31,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Facas",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 4000,
    purchaser: "",
  },
  {
    id: 32,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija de Vidro Marinex",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 1500,
    purchaser: "",
  },
  {
    id: 33,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Panela Churrasqueira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 7000,
    purchaser: "",
  },
  {
    id: 34,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Impressora sem cartucho",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 15000,
    purchaser: "",
  },
  {
    id: 35,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Garrafa Térmica com xícaras",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 36,
    urlPhoto: ["/product-photos/cortador-verduras-1.jpg", "/product-photos/cortador-verduras-2.jpg"],
    name: "Cortador de verduras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 37,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sapato Preto Masculino",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
    purchaser: "",
  },
  {
    id: 38,
    urlPhoto: "/product-photos/kit-potes-lilas-vidro-3pcs.jpg",
    name: "Kit 3 Potes Lilás de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
    purchaser: "",
  },
  {
    id: 39,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto 4 Potes de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 40,
    urlPhoto: "/product-photos/travessa-peixe-vidro.jpg",
    name: "Travessa Peixe Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 3000,
    purchaser: "",
  },
  {
    id: 41,
    urlPhoto: "/product-photos/mesa-infantil-verde.jpg",
    name: "Mesa Infantil Verde",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
    purchaser: "",
  },
  {
    id: 42,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Quadro Retangular",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 3000,
    purchaser: "",
  },
  {
    id: 43,
    urlPhoto: "/product-photos/bacia-grande-rosa.jpg",
    name: "Bacia Grande Rosa",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2500,
    purchaser: "",
  },
  {
    id: 44,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bacia Grande Vermelha",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2500,
    purchaser: "",
  },
  {
    id: 45,
    urlPhoto: "/product-photos/pipoqueira.jpg",
    name: "Pipoqueira Britania",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
    purchaser: "",
  },
  {
    id: 46,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cafeteira Oster",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
    purchaser: "",
  },
  {
    id: 47,
    urlPhoto: "/product-photos/tapioqueira.jpg",
    name: "Tapioqueira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 48,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jarra Vidro Água",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 49,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Condimento Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 50,
    urlPhoto: "/product-photos/jarra-licor.jpg",
    name: "Jarra Licor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 51,
    urlPhoto: "/product-photos/bandeija-bamboo.jpg",
    name: "Bandeija de Bamboo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 52,
    urlPhoto: "/product-photos/kit-bandeija-bamboo-potes.jpg",
    name: "Kit Bandeija Bamboo c/ 2 Potes",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 53,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Caneca Chá",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 0,
    purchaser: "",
  },
  {
    id: 54,
    urlPhoto: ["/product-photos/porta-colher-lyor-1.jpg", "/product-photos/porta-colher-lyor-2.jpg", "/product-photos/porta-colher-lyor-3.jpg"],
    name: "Porta colher Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 55,
    urlPhoto: ["/product-photos/kit-forma-hamburguer-tup-1.jpg", "/product-photos/kit-forma-hamburguer-tup-2.jpg", "/product-photos/kit-forma-hamburguer-tup-3.jpg", "/product-photos/kit-forma-hamburguer-tup-4.jpg", "/product-photos/kit-forma-hamburguer-tup-5.jpg"],
    name: "8 Forma Hamburguer Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 56,
    urlPhoto: "/product-photos/porta-guardanapos-8pc.jpg",
    name: "Kit 8 Porta Guardanapo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
    purchaser: "",
  },
  {
    id: 57,
    urlPhoto: "/product-photos/guardanapos-linho-8pcs.jpg",
    name: "Kit 8 Guardanapos de Linho",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
    purchaser: "",
  },
  {
    id: 58,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Espátula Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 59,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Jarrinhas",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 60,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pote Pequeno Love",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 61,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bule Pequeno Home",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 62,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Vasinho Listrado",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 63,
    urlPhoto: "/product-photos/porta-vela.jpg",
    name: "2 Porta Velas Preto",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 64,
    urlPhoto: "/product-photos/porta-retrato-vermelho.jpg",
    name: "Porta Retrato Vermelho",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 65,
    urlPhoto: ["/product-photos/prato-vidro-bolo-1.jpg", "/product-photos/prato-vidro-bolo-2.jpg"],
    name: "Prato de Vidro para Bolo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 66,
    urlPhoto: ["/product-photos/kit-prato-sobremesa-lyor-8pcs-1.jpg", "/product-photos/kit-prato-sobremesa-lyor-8pcs-2.jpg"],
    name: "Kit Pratos de Sobremesa Lyor 8pcs",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 10000,
    purchaser: "",
  },
  {
    id: 67,
    urlPhoto: ["/product-photos/prato-vidro-bolo-1.jpg", "/product-photos/prato-vidro-bolo-2.jpg"],
    name: "Prato de Vidro para Bolo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 68,
    urlPhoto: ["/product-photos/kit-copos-lyor-6pcs.jpg", "/product-photos/kit-copos-lyor-6pcs-2.jpg"],
    name: "6 Copos Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
    purchaser: "",
  },
  {
    id: 69,
    urlPhoto: "/product-photos/jarra-vidro-pequena.jpg",
    name: "Jarra de Vidro Pequena",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 70,
    urlPhoto: ["/product-photos/kit-tacas-licor-2pcs.jpg", "/product-photos/kit-tacas-licor-2pcs-2.jpg"],
    name: "2 Taças para Licor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 71,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Manteigueira",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 72,
    urlPhoto: ["/product-photos/kit-tacas-lanty-6pcs.jpg", "/product-photos/kit-tacas-lanty-6pcs-2.jpg"],
    name: "Kit Taças para Licor Lanty 6 pcs",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2500,
    purchaser: "",
  },
  {
    id: 73,
    urlPhoto: "/product-photos/casinha-wolff.jpg",
    name: "Casinha de Vidro Wolff",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 74,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Potes de Vidro Lilás",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 75,
    urlPhoto: "/product-photos/tigela-fiz.jpg",
    name: "Tigela Fiz",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 76,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Porta Copos Vidro",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1200,
    purchaser: "",
  },
  {
    id: 77,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Transparente",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 78,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Branco",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 500,
    purchaser: "",
  },
  {
    id: 79,
    urlPhoto: "/product-photos/copo-coca.jpg",
    name: "Copo Copa Coca Cola",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
    purchaser: "",
  },
  {
    id: 80,
    urlPhoto: "/product-photos/kit-facas-douradas-6pcs.jpg",
    name: "6 Facas Douradas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 81,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Espatulas Douradas",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 82,
    urlPhoto: "/product-photos/garfos-rose.jpg",
    name: "2 Garfos Rosê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 83,
    urlPhoto: "/product-photos/colheres-rose.jpg",
    name: "2 Colheres Rosê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 84,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "10 Colherzinhas Dourada",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 5000,
    purchaser: "",
  },
  {
    id: 85,
    urlPhoto: ["/product-photos/xicara-lyor-1.jpg", "/product-photos/xicara-lyor-2.jpg"],
    name: "2 Xícaras de Chá Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 86,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Garrafinhas de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 87,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jarra Espremedor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 88,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Mesa de Palha 8 Peças",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 5000,
    purchaser: "",
  },
  {
    id: 89,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Mesa Rosê 8 Peças",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 90,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "10 Palitos Petisco",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 91,
    urlPhoto: ["/product-photos/conjunto-pratos-pires-ryo-1.jpg", "/product-photos/conjunto-pratos-pires-ryo-2.jpg", "/product-photos/conjunto-pratos-pires-ryo-3.jpg", "/product-photos/conjunto-pratos-pires-ryo-4.jpg", "/product-photos/conjunto-pratos-pires-ryo-5.jpg"],
    name: "Jogo 4 Pratos & Pires Ryo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 10000,
    purchaser: "",
  },
  {
    id: 92,
    urlPhoto: ["/product-photos/conjunto-pratos-pires-ryo-1.jpg", "/product-photos/conjunto-pratos-pires-ryo-2.jpg", "/product-photos/conjunto-pratos-pires-ryo-3.jpg", "/product-photos/conjunto-pratos-pires-ryo-4.jpg", "/product-photos/conjunto-pratos-pires-ryo-5.jpg"],
    name: "Jogo 4 Pratos & Pires Ryo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 10000,
    purchaser: "",
  },
  {
    id: 93,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "3 Pratos de Vidro para Sobremesa",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 94,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Branco",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 500,
    purchaser: "",
  },
  {
    id: 95,
    urlPhoto: ["/product-photos/caixa-redonda-grande-lilas-tup-1.jpg", "/product-photos/caixa-redonda-grande-lilas-tup-2.jpg", "/product-photos/caixa-redonda-grande-lilas-tup-3.jpg"],
    name: "Caixa Redonda Grande Lilás Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 5000,
    purchaser: "",
  },
  {
    id: 96,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tigela Grande Tupperware",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
    purchaser: "",
  },
  {
    id: 97,
    urlPhoto: "/product-photos/prato-grande-salada.jpg",
    name: "Prato Grande Salada",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 98,
    urlPhoto: ["/product-photos/kit-pratos-salada-1.jpg", "/product-photos/kit-pratos-salada-2.jpg"],
    name: "Kit Pratos Salada 2 pcs",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 99,
    urlPhoto: "/product-photos/toalha-mesa-natal.jpg",
    name: "Toalha de Mesa Natal",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 100,
    urlPhoto: "/product-photos/toalha-mesa-natal.jpg",
    name: "Toalha de Mesa Natal",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 101,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Mop Amarelo",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 15000,
    purchaser: "",
  },
  {
    id: 102,
    urlPhoto: "/product-photos/kit-mesa-infantil-cadeiras.jpg",
    name: "Mesa Infantil com 2 Cadeiras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
    purchaser: "",
  },
  {
    id: 103,
    urlPhoto: "/product-photos/forma-gelatina.jpg",
    name: "Forma Gelatina Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 104,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Porta Vela",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 105,
    urlPhoto: ["/product-photos/kit-tacas-tup-4pcs-1.jpg", "/product-photos/kit-tacas-tup-4pcs-2.jpg", "/product-photos/kit-tacas-tup-4pcs-3.jpg", "/product-photos/kit-tacas-tup-4pcs-4.jpg"],
    name: "Kit 4 Taças Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 106,
    urlPhoto: ["/product-photos/tesoura-alimento-1.jpg", "/product-photos/tesoura-alimento-2.jpg", "/product-photos/tesoura-alimento-3.jpg"],
    name: "Tesoura para Alimento",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 107,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Fatiador de Tomates",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 108,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Corta Legumes",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 109,
    urlPhoto: ["/product-photos/kit-ovos-1.jpg", "/product-photos/kit-ovos-2.jpg", "/product-photos/kit-ovos-3.jpg"],
    name: "Kit para Ovos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 110,
    urlPhoto: ["/product-photos/saladeira-verde-tup-1.jpg", "/product-photos/saladeira-verde-tup-2.jpg"],
    name: "Saladeira Verde Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 111,
    urlPhoto: ["/product-photos/caixa-fina-branca-tup-1.jpg", "/product-photos/caixa-fina-branca-tup-2.jpg", "/product-photos/caixa-fina-branca-tup-3.jpg"],
    name: "Caixa Fina Branca Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 112,
    urlPhoto: ["/product-photos/caixa-retangular-grande-branca-tup-1.jpg", "/product-photos/caixa-retangular-grande-branca-tup-2.jpg"],
    name: "Caixa Retangular Grande Branca Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 113,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Queijo Tupperware",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 114,
    urlPhoto: ["/product-photos/caixa-retangular-pequena-rosa-tup-1.jpg", "/product-photos/caixa-retangular-pequena-rosa-tup-2.jpg", "/product-photos/caixa-retangular-pequena-rosa-tup-3.jpg"],
    name: "Caixa Retangular Pequena Rosa Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 115,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tampa Protetora Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 116,
    urlPhoto: "/product-photos/colher-grande.jpg",
    name: "Colher Grande",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 117,
    urlPhoto: "/product-photos/pegador-inox.jpg",
    name: "Pegador Inox",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 118,
    urlPhoto: ["/product-photos/caixa-retangular-grande-rosa-tup-1.jpg", "/product-photos/caixa-retangular-grande-rosa-tup-2.jpg", "/product-photos/caixa-retangular-grande-rosa-tup-3.jpg"],
    name: "Caixa Retangular Grande Rosa Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 119,
    urlPhoto: ["/product-photos/caixa-quadrada-grande-rosa-tup-1.jpg", "/product-photos/caixa-quadrada-grande-rosa-tup-2.jpg", "/product-photos/caixa-quadrada-grande-rosa-tup-3.jpg"],
    name: "Caixa Quadrada Grande Rosa Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
    purchaser: "",
  },
  {
    id: 120,
    urlPhoto: ["/product-photos/paozeira-tup-1.jpg", "/product-photos/paozeira-tup-2.jpg", "/product-photos/paozeira-tup-3.jpg"],
    name: "Pãozeira Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 121,
    urlPhoto: ["/product-photos/caixa-espacosa-branca-tup-1.jpg", "/product-photos/caixa-espacosa-branca-tup-2.jpg", "/product-photos/caixa-espacosa-branca-tup-3.jpg"],
    name: "Caixa Espaçosa Branca Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 122,
    urlPhoto: "/product-photos/amassador-tup.jpg",
    name: "Amassador Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 123,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Ralador Chef",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 124,
    urlPhoto: "/product-photos/kit-colher-bamboo-4pcs.jpg",
    name: "Kit 4 Colheres Bamboo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 125,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto 6 Assentos de Cadeira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 126,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit 6 Assentos de Cadeira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 127,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit 4 Assentos de Cadeira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 128,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália Bege",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 5000,
    purchaser: "",
  },
  {
    id: 129,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália Picadilli",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  },
  {
    id: 130,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália Rosê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 5000,
    purchaser: "",
  },
  {
    id: 131,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 132,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Quadro de Madeira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 60000,
    purchaser: "",
  },
  {
    id: 133,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho Bebê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 30000,
    purchaser: "",
  },
  {
    id: 134,
    urlPhoto: ["/product-photos/cadeirinha-bebe-1.jpg", "/product-photos/cadeirinha-bebe-2.jpg"],
    name: "Cadeirinha de Bebê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
    purchaser: "",
  },
  {
    id: 135,
    urlPhoto: ["/product-photos/conjunto-pizane-mesa-cadeiras-1.jpg", "/product-photos/conjunto-pizane-mesa-cadeiras-2.jpg", "/product-photos/conjunto-pizane-mesa-cadeiras-3.jpg", "/product-photos/conjunto-pizane-mesa-cadeiras-4.jpg"],
    name: "Conjunto Pizane Mesa & 4 Cadeiras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 18000,
    purchaser: "",
  },
  {
    id: 136,
    urlPhoto: ["/product-photos/conjunto-pizane-mesa-cadeiras-1.jpg", "/product-photos/conjunto-pizane-mesa-cadeiras-2.jpg"],
    name: "Conjunto Pizane Mesa & 4 Cadeiras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 18000,
    purchaser: "",
  },
  {
    id: 137,
    urlPhoto: "/product-photos/garrafa-tup.jpg",
    name: "Garrafa Tupperware",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 138,
    urlPhoto: "/product-photos/oculos.jpg",
    name: "Óculos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 139,
    urlPhoto: "/product-photos/coletes-infantis-piscina.jpg",
    name: "2 Coletes Infantis para Piscina",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 140,
    urlPhoto: ["/product-photos/kit-guardanapos-amarelos-8pcs-2.jpg", "/product-photos/kit-guardanapos-amarelos-8pcs-1.jpg"],
    name: "Kit 8 Guardanapos Amarelos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 141,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho de Decoração",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 142,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho de Decoração",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 143,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Fonte Madeira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 144,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho Infantil",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 145,
    urlPhoto: ["/product-photos/porta-alho-tup-1.jpg", "/product-photos/porta-alho-tup-2.jpg"],
    name: "Porta Alho Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 146,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortina",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 147,
    urlPhoto: "/product-photos/espatula-preta.jpg",
    name: "Espátula Preta",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
    purchaser: "",
  },
  {
    id: 148,
    urlPhoto: "/product-photos/porta-tempero-verde-tup.jpg",
    name: "Porta Tempero Verde Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
    purchaser: "",
  },
  {
    id: 149,
    urlPhoto: "/product-photos/vaso-ceramica-decoracao.jpg",
    name: "Vaso Cerâmica Decoração",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
    purchaser: "",
  },
  {
    id: 150,
    urlPhoto: "/product-photos/porta-joia-vidro.jpg",
    name: "Porta Joias Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
    purchaser: "",
  },
  {
    id: 151,
    urlPhoto: "/product-photos/bico-lillo.jpg",
    name: "Bico Lillo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
    purchaser: "",
  },
  {
    id: 152,
    urlPhoto: "/product-photos/separador-gema-tup.jpg",
    name: "Separador de Gema Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 0,
    purchaser: "",
  },
  {
    id: 153,
    urlPhoto: ["/product-photos/retrato-marrom-1.jpg", "/product-photos/retrato-marrom-2.jpg"],
    name: "Porta Retrato Marrom",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 154,
    urlPhoto: "/product-photos/vaso-pedra-decorativo.jpg",
    name: "Vaso Pedra Decorativo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
    purchaser: "",
  },
  {
    id: 155,
    urlPhoto: "/product-photos/pedrinhas-laranjas-decoracao.jpg",
    name: "Pedrinhas Laranjas Decoração",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
    purchaser: "",
  },
  {
    id: 156,
    urlPhoto: "/product-photos/banheira-branca.jpg",
    name: "Banheira Hércules Branca",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 0,
    purchaser: "",
  },
  {
    id: 157,
    urlPhoto: "/product-photos/kit-almofada-cadeira.jpg",
    name: "Kit Almofadas de Cadeira 4 peças",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
    purchaser: "",
  },
  {
    id: 158,
    urlPhoto: "/product-photos/kit-almofada-cadeira.jpg",
    name: "Kit Almofadas de Cadeira 6 peças",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
    purchaser: "",
  }
]

