import { Product, Supplier } from "./product.types"

export const productData: Product[] = [
  {
    id: 1,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 2,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboniere Vidro Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 3,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboniere Vidro",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 4,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de pratos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 5,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Condimentos Giratorio",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 6,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Chaleira Cinza",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 8000,
  },
  {
    id: 7,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto de pratos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 5000,
  },
  {
    id: 8,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Chaleira Pequena",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 9,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Potes Pequenos Microondas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1000,
  },
  {
    id: 10,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cafeteira Nespresso",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 20000,
  },
  {
    id: 11,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bule Chá",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1500,
  },
  {
    id: 12,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Queijo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 3000,
  },
  {
    id: 13,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Suporte Café",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 1000,
  },
  {
    id: 14,
    urlPhoto: "/product-photos/kit-potes-vidro-palha-2pcs.jpg",
    name: "2 Potes Vidro Palha",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 4000,
  },
  {
    id: 15,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sanduicheira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.MIRIAM,
    price: 4000,
  },
  {
    id: 16,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Ovos Galinha",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 1200,
  },
  {
    id: 17,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Ovos Bege",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 18,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Garrafa Térmica 1L",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 19,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "1 Cortina Bege",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
  },
  {
    id: 20,
    urlPhoto: ["/product-photos/pote-pera-chocolate-1.jpg", "/product-photos/pote-pera-chocolate-2.jpg"],
    name: "Pote Pêra Chocolate",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 21,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pote Laranja",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 22,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto Listrado Verde",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
  },
  {
    id: 23,
    urlPhoto: "/product-photos/prato-microondas.jpg",
    name: "Prato Microondas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1500,
  },
  {
    id: 24,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 25,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortina",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 6000,
  },
  {
    id: 26,
    urlPhoto: "/product-photos/maquina-donuts.jpg",
    name: "Maquina de fazer Donuts",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 8000,
  },
  {
    id: 27,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bomboneira/Doceira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 28,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 0,
  },
  {
    id: 29,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Termometro de cozinha",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1500,
  },
  {
    id: 30,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Luva & Avental",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 31,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Facas",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 4000,
  },
  {
    id: 32,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija de Vidro Marinex",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 1500,
  },
  {
    id: 33,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Panela Churrasqueira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 7000,
  },
  {
    id: 34,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Impressora sem cartucho",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 15000,
  },
  {
    id: 35,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Garrafa Térmica com xícaras",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 36,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortador de verduras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 37,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sapato Preto Masculino",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 5000,
  },
  {
    id: 38,
    urlPhoto: "/product-photos/kit-potes-lilas-vidro-3pcs.jpg",
    name: "Kit 3 Potes Lilás de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 39,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto 4 Potes de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 40,
    urlPhoto: "/product-photos/travessa-peixe-vidro.jpg",
    name: "Travessa Peixe Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 3000,
  },
  {
    id: 41,
    urlPhoto: "/product-photos/mesa-infantil-verde.jpg",
    name: "Mesa Infantil Verde",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 2000,
  },
  {
    id: 42,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Quadro Retangular",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.LENI,
    price: 3000,
  },
  {
    id: 43,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bacia Grande Rosa",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2500,
  },
  {
    id: 44,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bacia Grande Vermelha",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2500,
  },
  {
    id: 45,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pipoqueira Britania",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
  },
  {
    id: 46,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cafeteira Oster",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
  },
  {
    id: 47,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tapioqueira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 48,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jarra Vidro Água",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 49,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Condimento Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 50,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jarra Licor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 51,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bandeija de Bamboo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 52,
    urlPhoto: "/product-photos/kit-bandeija-bamboo-potes.jpg",
    name: "Kit Bandeija Bamboo c/ 2 Potes",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 53,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Caneca Chá",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 0,
  },
  {
    id: 54,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta colher Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 55,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "8 Forma Hamburguer Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 56,
    urlPhoto: "/product-photos/porta-guardanapos-8pc.jpg",
    name: "Kit 8 Porta Guardanapo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
  },
  {
    id: 57,
    urlPhoto: "/product-photos/guardanapos-linho-8pcs.jpg",
    name: "Kit 8 Guardanapos de Linho",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
  },
  {
    id: 58,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Espátula Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 59,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Jarrinhas",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 60,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pote Pequeno Love",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 61,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Bule Pequeno Home",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 62,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Vasinho Listrado",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 63,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Porta Velas Preto",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 64,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Retrato",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 65,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato de Vidro para Bolo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 66,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "8 Pratos de Sobremesa Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 10000,
  },
  {
    id: 67,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato de Vidro para Bolo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 68,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "6 Copos Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
  },
  {
    id: 69,
    urlPhoto: "/product-photos/jarra-vidro-pequena.jpg",
    name: "Jarra de Vidro Pequena",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 70,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Taças para Licor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 71,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Manteigueira",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 72,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "6 Taças para Licor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2500,
  },
  {
    id: 73,
    urlPhoto: "/product-photos/casinha-wolff.jpg",
    name: "Casinha de Vidro Wolff",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 74,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Potes de Vidro Lilás",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 75,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tigela Fiz",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 76,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Porta Copos Vidro",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1200,
  },
  {
    id: 77,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Transparente",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 78,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Branco",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 500,
  },
  {
    id: 79,
    urlPhoto: "/product-photos/copo-coca.jpg",
    name: "Copo Copa Coca Cola",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
  },
  {
    id: 80,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "6 Facas Douradas",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 81,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Espatulas Douradas",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 82,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Garfos Rosê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 83,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Colheres Rosê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 84,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "10 Colherzinhas Dourada",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 5000,
  },
  {
    id: 85,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Xícaras de Chá Lyor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 86,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Garrafinhas de Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 87,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jarra Espremedor",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 88,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Mesa de Palha 8 Peças",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 5000,
  },
  {
    id: 89,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo de Mesa Rosê 8 Peças",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 90,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "10 Palitos Petisco",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 91,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo 4 Pratos/Pires Ryo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 10000,
  },
  {
    id: 92,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Jogo 4 Pratos/Pires Ryo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 10000,
  },
  {
    id: 93,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "3 Pratos de Vidro para Sobremesa",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 94,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Prato Branco",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 500,
  },
  {
    id: 95,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Forma Redonda Grande Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 5000,
  },
  {
    id: 96,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tigela Grande Tupperware",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
  },
  {
    id: 97,
    urlPhoto: "/product-photos/prato-grande-salada.jpg",
    name: "Prato Grande Salada",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 98,
    urlPhoto: ["/product-photos/kit-pratos-salada-1.jpg", "/product-photos/kit-pratos-salada-2.jpg"],
    name: "Kit Pratos Salada 2 pcs",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 99,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Toalha de Mesa Natal",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 100,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Toalha de Mesa Natal",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 101,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Mop Amarelo",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 15000,
  },
  {
    id: 102,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Mesa Infantil com 2 Cadeiras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
  },
  {
    id: 103,
    urlPhoto: "/product-photos/forma-gelatina.jpg",
    name: "Forma Gelatina Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 104,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "2 Porta Vela",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 105,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "4 Taças Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 106,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tesoura para Alimento",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 107,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Fatiador de Tomates",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 108,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Corta Legumes",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 109,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit para Ovos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 110,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Saladeira Verde",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 111,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Forma Lilás Tupperware para Bife",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 112,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Forma Trnasparente Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 113,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Queijo Tupperware",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 114,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Caixa Retangular Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 115,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Tampa Protetora Inox",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 116,
    urlPhoto: "/product-photos/colher-grande.jpg",
    name: "Colher Grande",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 117,
    urlPhoto: "/product-photos/pegador-inox.jpg",
    name: "Pegador Inox",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 118,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Caixa Retangular Grande",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 119,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Caixa Quadrada Grande Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 6000,
  },
  {
    id: 120,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Pãozeira Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 121,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Caixa Espaçosa Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 122,
    urlPhoto: "/product-photos/amassador-tup.jpg",
    name: "Amassador Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 123,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Ralador Chef",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 124,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit 4 Colheres Bamboo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 125,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto 6 Assentos de Cadeira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 126,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit 6 Assentos de Cadeira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 127,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit 4 Assentos de Cadeira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 128,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália Bege",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 5000,
  },
  {
    id: 129,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália Picadilli",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 4000,
  },
  {
    id: 130,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália Rosê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 5000,
  },
  {
    id: 131,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Sandália",
    isAvailable: false,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 3000,
  },
  {
    id: 132,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Quadro de Madeira",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 60000,
  },
  {
    id: 133,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho Bebê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 30000,
  },
  {
    id: 134,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cadeirinha de Bebê",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 8000,
  },
  {
    id: 135,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto Mesa & 4 Cadeiras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 18000,
  },
  {
    id: 136,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Conjunto Mesa & 4 Cadeiras",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 18000,
  },
  {
    id: 137,
    urlPhoto: "/product-photos/garrafa-tup.jpg",
    name: "Garrafa Tupperware",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 138,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Óculos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 139,
    urlPhoto: "/product-photos/coletes-infantis-piscina.jpg",
    name: "2 Coletes Infantis para Piscina",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 140,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Kit 8 Guardanapos Amarelos",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 141,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho de Decoração",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 142,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho de Decoração",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 143,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Fonte Madeira",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 144,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Carrinho Infantil",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 145,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Porta Alho Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 146,
    urlPhoto: "/product-photos/placeholder.svg",
    name: "Cortina",
    isAvailable: false,
    isPaid: true,
    supplier: Supplier.JEU,
    price: 2000,
  },
  {
    id: 147,
    urlPhoto: "/product-photos/espatula-preta.jpg",
    name: "Espátula Preta",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
  },
  {
    id: 148,
    urlPhoto: "/product-photos/porta-tempero-verde-tup.jpg",
    name: "Porta Tempero Verde Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.LENI,
    price: 1000,
  },
  {
    id: 149,
    urlPhoto: "/product-photos/vaso-ceramica-decoracao.jpg",
    name: "Vaso Cerâmica Decoração",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1500,
  },
  {
    id: 150,
    urlPhoto: "/product-photos/porta-joia-vidro.jpg",
    name: "Porta Joias Vidro",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 500,
  },
  {
    id: 151,
    urlPhoto: "/product-photos/bico-lillo.jpg",
    name: "Bico Lillo",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 1000,
  },
  {
    id: 152,
    urlPhoto: "/product-photos/separador-gema-tup.jpg",
    name: "Separador de Gema Tupperware",
    isAvailable: true,
    isPaid: false,
    supplier: Supplier.JEU,
    price: 0,
  },
]
